/**
 * Reputera Reviews product content.
 *
 * `plan` marks which tier a capability belongs to and drives the badge on each
 * card — 'all' for everything included at every tier, 'growth' for the ones
 * that start at Growth.
 */

export type ReviewsFeature = {
  title: string;
  body: string;
  plan: 'all' | 'growth';
};

export const reviewsPositioning =
  'Reputera is reputation management for local businesses, sold to the agencies that serve them.';

export const reviewsFeatures: ReviewsFeature[] = [
  {
    title: 'Automatic review collection',
    body: 'Reviews are pulled from Google on a schedule per business. No copy-pasting, no logging into a dozen Google accounts.',
    plan: 'all',
  },
  {
    title: 'AI-drafted responses',
    body: "Every review gets a reply drafted in that business's brand voice, language, and sign-off style — then a human approves it. Nothing publishes unreviewed.",
    plan: 'all',
  },
  {
    title: 'One-click publishing to Google',
    body: 'Approved replies post straight to the Google Business Profile through the official API.',
    plan: 'all',
  },
  {
    title: 'Sentiment & crisis detection',
    body: 'Each review is analysed for sentiment and flagged if it needs urgent human attention, so a reputation fire never sits unnoticed.',
    plan: 'all',
  },
  {
    title: 'Review invitation campaigns',
    body: 'Upload a customer list, pick email or WhatsApp (or both), and invite past customers to leave a review. Full funnel tracking: sent, delivered, read, clicked.',
    plan: 'all',
  },
  {
    title: 'Printable review QR codes',
    body: 'Download a QR for any business that links straight to its Google review page. Print it, stick it on the counter — it keeps working forever.',
    plan: 'all',
  },
  {
    title: 'Premium AI share cards',
    body: 'Turn a great review into a designed social graphic in three styles — Noir Luxe, Vivid Pulse, Gallery White — generated by AI, ready to post.',
    plan: 'all',
  },
  {
    title: 'Embeddable review widgets',
    body: "Drop a live review widget on the business's own website.",
    plan: 'all',
  },
  {
    title: 'Reports & insights',
    body: "Scheduled PDF reports and a trends dashboard — what customers praise, what they complain about, how it's moving.",
    plan: 'all',
  },
  {
    title: 'Team seats & scoped access',
    body: "Invite teammates and assign each one exactly the businesses they should see. Nobody sees a client they don't work on.",
    plan: 'growth',
  },
];

export const planLabel: Record<ReviewsFeature['plan'], string> = {
  all: 'All plans',
  growth: 'Growth+',
};

/**
 * The high-level benefits, kept alongside the detailed capability list: this
 * section frames the outcome, the feature grid below spells out what ships.
 */
export const reviewsBenefits = [
  {
    title: 'Collect more reviews',
    body: 'Invitation campaigns by email and WhatsApp, plus printable QR codes, so happy customers are asked at the moment they are most likely to say something good.',
  },
  {
    title: 'Monitor as they land',
    body: 'New Google reviews are pulled in on a schedule and analysed for sentiment, so nothing negative sits unanswered for a fortnight.',
  },
  {
    title: 'Reply without the grind',
    body: 'Replies are drafted in the business’s own voice, ready for a human to approve and publish — turning an hour of writing into a couple of minutes.',
  },
  {
    title: 'See the trend',
    body: 'Rating over time, review volume and what customers keep mentioning — the signal underneath the star count, in scheduled reports and a live dashboard.',
  },
];
